name: Build OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 释放磁盘空间
        uses: easimon/maximize-build-space@v1
        with:
          root-reserve-mb: 1024
          swap-size-mb: 2048
          remove-dotnet: true
          remove-haskell: true
          remove-android: true
          remove-docker-images: true
          
      - name: 检查磁盘空间
        run: df -h
        
      - name: 检出 OpenWrt 代码
        uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: master
          submodules: recursive
          
      - name: 更新 feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: 配置编译选项
        run: |
          make defconfig
          sed -i 's/CONFIG_DEBUG_INFO=y/# CONFIG_DEBUG_INFO is not set/' .config
          echo 'CONFIG_CCACHE=y' >> .config
          echo 'CONFIG_KERNEL_CCACHE=y' >> .config
